import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  adjustFontFallback: false,
  display: "swap",
  fallback: ["Helvetica", "Arial", "sans-serif"],
  preload: true,
  style: "normal",
});

export const metadata: Metadata = {
  title: "E-Summit 2026",
  description: "Generated by create next app",
  icons: {
    icon: "/E_Fav.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
